### ISSUE TITLE
Error: Could not parse package: '\--- org.projectlombok:lombok (n)' (1)

### ISSUE THREAD

**Issue by Srinath22N** [mikepenz/gradle-dependency-submission#141]
Currently using v0.8.0. The action is failing with the following error

`Error: Could not parse package: '\--- org.projectlombok:lombok (n)' (1)`

Dependency output

```
compileClasspath - Compile classpath for source set 'main'.

+--- org.projectlombok:lombok -> 1.18.16

```

**Comment by Srinath22N** [comment]
@mikepenz

**Comment by Srinath22N** [comment]
```
`/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68
          throw Error(`The given '${pkg} can't be parsed as a gradle package.`);
 ^
 Error: The given '\--- org.projectlombok:lombok (n) can't be parsed as a gradle package.
    at parseGradlePackage (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68:1)
     at parseGradleDependency (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:166:1)
     at parseGradleGraph (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:117:1)
     at /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:195:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:28:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)`
```
