### ISSUE TITLE
Error: The given '\--- unspecified (n) can't be parsed as a gradle package.

### ISSUE THREAD

**Issue by Srinath22N** [mikepenz/gradle-dependency-submission#168]
```
Dependency output of 1854 lines
Warning: Discovered unresolved dependency: \--- org.projectlombok:lombok (n)
Warning: Discovered unresolved dependency: +--- org.springframework.boot:spring-boot-starter-actuator (n)
Warning: Discovered unresolved dependency: +--- org.springframework.boot:spring-boot-starter-jetty (n)
Warning: Discovered unresolved dependency: +--- org.springframework.boot:spring-boot-starter-data-jpa (n)
Warning: Discovered unresolved dependency: +--- org.springframework.boot:spring-boot-starter-security (n)
Warning: Discovered unresolved dependency: +--- org.springframework.boot:spring-boot-starter-web (n)
Warning: Discovered unresolved dependency: +--- org.flywaydb:flyway-core (n)
Error: Could not parse package: '\--- unspecified (n)' (2)  /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/parse.js:79
         throw Error(`The given '${pkg} can't be parsed as a gradle package.`);
 ^
Error: The given '\--- unspecified (n) can't be parsed as a gradle package.
at parseGradlePackage (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/parse.js:79:1)
at parseGradleDependency (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/parse.js:172:1)
at parseGradleGraph (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/parse.js:123:1)
at /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/process.js:195:1
at Generator.next (<anonymous>)
at fulfilled (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.2/webpack:/gradle-dependency-submission/lib/process.js:28:1)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Let me know if you need any additional information. Thank you.

**Comment by Srinath22N** [comment]
@mikepenz

**Comment by mikepenz** [comment]
@Srinath22N `unspecified` is not a valid package. 

While I agree that it should not fail the whole process of the action - please have a look into your project setup as this may indicate a problem

**Comment by Srinath22N** [comment]
Unspecified is due to a private inbuilt package. Is there a way we could ignore it?
