### ISSUE TITLE
Action fails with Null-Pointer error

### ISSUE THREAD

**Issue by buehlerjochen** [mikepenz/gradle-dependency-submission#344]
Hi,

today I wanted to add the dependency scan to another repository and got an exception, which I was not able to diagnose and solve on my own.

The error occurrs when the plugin prepares to submit the dependencies. I don't know if the parsing of the dependencies causes the problem, but the generated dependency list looks fine. But the problem seems to be specific to this project as the scan in the other (older) repo still works.

We are using plugin version 0.9.0, but I get the same error with 0.8.6. Gradle version is 7.6, but the error also occurrs on 7.5.1.

The action fails with this error:
```
2023-08-25T06:28:36.0357196Z ##[error]Cannot read properties of null (reading 'toString')
2023-08-25T06:28:36.1446109Z ##[error]TypeError: Cannot read properties of null (reading 'toString')
    at /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:506:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-25T06:28:36.1519863Z 
2023-08-25T06:28:36.1521300Z /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395
2023-08-25T06:28:36.1522139Z         function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
2023-08-25T06:28:36.1523114Z ^
2023-08-25T06:28:36.1541706Z Error: Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
2023-08-25T06:28:36.1542771Z     at /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:520:1
2023-08-25T06:28:36.1543465Z     at Generator.next (<anonymous>)
2023-08-25T06:28:36.1544384Z     at fulfilled (/home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
2023-08-25T06:28:36.1545140Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
It looks like an error when accessing a null value, but I can not find out which value is not set as expceted.

The full log is:
```
2023-08-25T06:28:15.8644877Z ##[group]Run mikepenz/gradle-dependency-submission@v0.9.0
2023-08-25T06:28:15.8645337Z with:
2023-08-25T06:28:15.8645724Z   gradle-build-module: :
2023-08-25T06:28:15.8646225Z   gradle-build-configuration: compileClasspath
2023-08-25T06:28:15.8646907Z   token: ***
2023-08-25T06:28:15.8647248Z   use-gradlew: true
2023-08-25T06:28:15.8647644Z   sub-module-mode: IGNORE
2023-08-25T06:28:15.8648094Z   include-build-environment: false
2023-08-25T06:28:15.8648474Z   fail-on-error: false
2023-08-25T06:28:15.8648871Z   legacy-support: false
2023-08-25T06:28:15.8649215Z env:
2023-08-25T06:28:15.8649734Z   JAVA_HOME_11_x64: /home/build/ghactions/myProject/runner1/_work/_tool/jdk/11.0.16/x64
2023-08-25T06:28:15.8650270Z   JAVA_HOME: /home/build/ghactions/myProject/runner1/_work/_tool/jdk/11.0.16/x64
2023-08-25T06:28:15.8650825Z   JAVA_HOME_11_X64: /home/build/ghactions/myProject/runner1/_work/_tool/jdk/11.0.16/x64
2023-08-25T06:28:15.8651264Z ##[endgroup]
2023-08-25T06:28:16.0027901Z ##[group]📘 Reading input values
2023-08-25T06:28:16.0043754Z ##[endgroup]
2023-08-25T06:28:16.0050290Z ##[group]🔨 Processing gradle dependencies for root module - ':'
2023-08-25T06:28:30.5730299Z Completed retrieving the 'dependencies' for configuration 'compileClasspath' within 14567ms
2023-08-25T06:28:30.5731832Z ##[endgroup]
2023-08-25T06:28:30.5733532Z ##[group]📄 Parsing gradle dependencies graph - ':'
2023-08-25T06:28:30.5733942Z Dependency output of 96 lines
2023-08-25T06:28:30.5750736Z Completed parsing 59 dependency associations within 2ms
2023-08-25T06:28:30.5753055Z ##[endgroup]
2023-08-25T06:28:33.3193527Z ##[group]📦️ Preparing Dependency Snapshot - ':'
2023-08-25T06:28:35.8401143Z Connection 13 direct dependencies
2023-08-25T06:28:35.8404899Z Connection 25 indirect dependencies
2023-08-25T06:28:35.8408531Z ##[endgroup]
2023-08-25T06:28:35.8474663Z ##[notice]Submitting snapshot...
2023-08-25T06:28:35.8524872Z ##[notice]{
    "detector": {
        "name": "mikepenz/gradle-dependency-submission",
        "url": "https://github.com/mikepenz/gradle-dependency-submission",
        "version": "v1.0.1"
    },
    "version": 0,
    "job": {
        "correlator": "security-scan-:-compileClasspath",
        "id": "2694090"
    },
    "sha": "71277e324abadefee9d24f184e89b2177ddb7da1",
    "ref": "refs/heads/feature/MYTICKET-840-add-security-scan",
    "scanned": "2023-08-25T06:28:35.840Z",
    "manifests": {
        "myApplication": {
            "resolved": {
                "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8@1.7.21": {
                    "package_url": "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8@1.7.21",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk7@1.7.21"
                    ]
                },
                "pkg:maven/com.our.own.project1/project1@1.0.0": {
                    "package_url": "pkg:maven/com.our.own.project1/project1@1.0.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.springframework.statemachine/spring-statemachine-core@3.2.0",
                        "pkg:maven/com.hivemq/hivemq-mqtt-client@1.3.0",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8@1.7.21"
                    ]
                },
                "pkg:maven/com.bosch.myProject.jdpdu/jdpdu@7.2.0": {
                    "package_url": "pkg:maven/com.bosch.myProject.jdpdu/jdpdu@7.2.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8@1.7.21"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-json@1.3.3": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-json@1.3.3",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm@1.3.3"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core@1.6.4": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core@1.6.4",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm@1.6.4"
                    ]
                },
                "pkg:maven/org.springframework.statemachine/spring-statemachine-core@3.2.0": {
                    "package_url": "pkg:maven/org.springframework.statemachine/spring-statemachine-core@3.2.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-tx@5.3.19",
                        "pkg:maven/org.springframework/spring-messaging@5.3.19",
                        "pkg:maven/io.projectreactor/reactor-core@3.4.17"
                    ]
                },
                "pkg:maven/org.springframework/spring-context@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-context@5.3.22",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-aop@5.3.22",
                        "pkg:maven/org.springframework/spring-beans@5.3.22",
                        "pkg:maven/org.springframework/spring-core@5.3.22",
                        "pkg:maven/org.springframework/spring-expression@5.3.22"
                    ]
                },
                "pkg:maven/com.hivemq/hivemq-mqtt-client@1.3.0": {
                    "package_url": "pkg:maven/com.hivemq/hivemq-mqtt-client@1.3.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/io.reactivex.rxjava2/rxjava@2.2.19",
                        "pkg:maven/org.reactivestreams/reactive-streams@1.0.3"
                    ]
                },
                "pkg:maven/com.hivemq/hivemq-mqtt-client-websocket@1.3.0": {
                    "package_url": "pkg:maven/com.hivemq/hivemq-mqtt-client-websocket@1.3.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/com.hivemq/hivemq-mqtt-client@1.3.0"
                    ]
                },
                "pkg:maven/com.hivemq/hivemq-mqtt-client-proxy@1.3.0": {
                    "package_url": "pkg:maven/com.hivemq/hivemq-mqtt-client-proxy@1.3.0",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/com.hivemq/hivemq-mqtt-client@1.3.0"
                    ]
                },
                "pkg:maven/org.slf4j/slf4j-api@1.7.36": {
                    "package_url": "pkg:maven/org.slf4j/slf4j-api@1.7.36",
                    "relationship": "direct",
                    "dependencies": []
                },
                "pkg:maven/info.picocli/picocli@4.6.3": {
                    "package_url": "pkg:maven/info.picocli/picocli@4.6.3",
                    "relationship": "direct",
                    "dependencies": []
                },
                "pkg:maven/ch.qos.logback/logback-classic@1.2.11": {
                    "package_url": "pkg:maven/ch.qos.logback/logback-classic@1.2.11",
                    "relationship": "direct",
                    "dependencies": [
                        "pkg:maven/ch.qos.logback/logback-core@1.2.11",
                        "pkg:maven/org.slf4j/slf4j-api@1.7.36"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21": {
                    "package_url": "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21",
                        "pkg:maven/org.jetbrains/annotations@13.0"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21": {
                    "package_url": "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21",
                    "relationship": "indirect",
                    "dependencies": []
                },
                "pkg:maven/org.jetbrains/annotations@13.0": {
                    "package_url": "pkg:maven/org.jetbrains/annotations@13.0",
                    "relationship": "indirect",
                    "dependencies": []
                },
                "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk7@1.7.21": {
                    "package_url": "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk7@1.7.21",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21"
                    ]
                },
                "pkg:maven/org.springframework/spring-tx@5.3.19": {
                    "package_url": "pkg:maven/org.springframework/spring-tx@5.3.19",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-beans@5.3.22",
                        "pkg:maven/org.springframework/spring-core@5.3.22"
                    ]
                },
                "pkg:maven/org.springframework/spring-beans@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-beans@5.3.22",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-core@5.3.22"
                    ]
                },
                "pkg:maven/org.springframework/spring-core@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-core@5.3.22",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-jcl@5.3.22"
                    ]
                },
                "pkg:maven/org.springframework/spring-jcl@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-jcl@5.3.22",
                    "relationship": "indirect",
                    "dependencies": []
                },
                "pkg:maven/org.springframework/spring-messaging@5.3.19": {
                    "package_url": "pkg:maven/org.springframework/spring-messaging@5.3.19",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-beans@5.3.22",
                        "pkg:maven/org.springframework/spring-core@5.3.22"
                    ]
                },
                "pkg:maven/io.projectreactor/reactor-core@3.4.17": {
                    "package_url": "pkg:maven/io.projectreactor/reactor-core@3.4.17",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.reactivestreams/reactive-streams@1.0.3"
                    ]
                },
                "pkg:maven/org.reactivestreams/reactive-streams@1.0.3": {
                    "package_url": "pkg:maven/org.reactivestreams/reactive-streams@1.0.3",
                    "relationship": "indirect",
                    "dependencies": []
                },
                "pkg:maven/io.reactivex.rxjava2/rxjava@2.2.19": {
                    "package_url": "pkg:maven/io.reactivex.rxjava2/rxjava@2.2.19",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.reactivestreams/reactive-streams@1.0.3"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm@1.3.3": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-json-jvm@1.3.3",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21",
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core@1.3.3"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core@1.3.3": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core@1.3.3",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core-jvm@1.3.3"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core-jvm@1.3.3": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-serialization-core-jvm@1.3.3",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib@1.7.21",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm@1.6.4": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm@1.6.4",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-bom@1.6.4",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-jdk8@1.7.21",
                        "pkg:maven/org.jetbrains.kotlin/kotlin-stdlib-common@1.7.21"
                    ]
                },
                "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-bom@1.6.4": {
                    "package_url": "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-bom@1.6.4",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core-jvm@1.6.4",
                        "pkg:maven/org.jetbrains.kotlinx/kotlinx-coroutines-core@1.6.4"
                    ]
                },
                "pkg:maven/org.springframework/spring-aop@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-aop@5.3.22",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-beans@5.3.22",
                        "pkg:maven/org.springframework/spring-core@5.3.22"
                    ]
                },
                "pkg:maven/org.springframework/spring-expression@5.3.22": {
                    "package_url": "pkg:maven/org.springframework/spring-expression@5.3.22",
                    "relationship": "indirect",
                    "dependencies": [
                        "pkg:maven/org.springframework/spring-core@5.3.22"
                    ]
                },
                "pkg:maven/ch.qos.logback/logback-core@1.2.11": {
                    "package_url": "pkg:maven/ch.qos.logback/logback-core@1.2.11",
                    "relationship": "indirect",
                    "dependencies": []
                }
            },
            "name": "myApplication",
            "file": {
                "source_location": "build.gradle"
            }
        }
    }
}
2023-08-25T06:28:35.8567914Z ##[endgroup]
2023-08-25T06:28:36.0357196Z ##[error]Cannot read properties of null (reading 'toString')
2023-08-25T06:28:36.1446109Z ##[error]TypeError: Cannot read properties of null (reading 'toString')
    at /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:506:1
    at Generator.next (<anonymous>)
    at fulfilled (/home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-25T06:28:36.1519863Z 
2023-08-25T06:28:36.1521300Z /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395
2023-08-25T06:28:36.1522139Z         function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
2023-08-25T06:28:36.1523114Z ^
2023-08-25T06:28:36.1541706Z Error: Failed to submit snapshot: TypeError: Cannot read properties of null (reading 'toString')
2023-08-25T06:28:36.1542771Z     at /home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:520:1
2023-08-25T06:28:36.1543465Z     at Generator.next (<anonymous>)
2023-08-25T06:28:36.1544384Z     at fulfilled (/home/build/ghactions/myProject/runner1/_work/_actions/mikepenz/gradle-dependency-submission/v0.9.0/webpack:/gradle-dependency-submission/node_modules/@github/dependency-submission-toolkit/dist/index.js:395:1)
2023-08-25T06:28:36.1545140Z     at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

If it helps for testing, this is the Gradle dependency output:
```
compileClasspath - Compile classpath for compilation 'main' (target  (jvm)).
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.7.21
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.7.21
|    |    \--- org.jetbrains:annotations:13.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.7.21
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.7.21 (*)
+--- com.our.own.project1:project1:1.0.0
|    +--- org.springframework.statemachine:spring-statemachine-core:3.2.0
|    |    +--- org.springframework:spring-tx:5.3.19
|    |    |    +--- org.springframework:spring-beans:5.3.19 -> 5.3.22
|    |    |    |    \--- org.springframework:spring-core:5.3.22
|    |    |    |         \--- org.springframework:spring-jcl:5.3.22
|    |    |    \--- org.springframework:spring-core:5.3.19 -> 5.3.22 (*)
|    |    +--- org.springframework:spring-messaging:5.3.19
|    |    |    +--- org.springframework:spring-beans:5.3.19 -> 5.3.22 (*)
|    |    |    \--- org.springframework:spring-core:5.3.19 -> 5.3.22 (*)
|    |    \--- io.projectreactor:reactor-core:3.4.17
|    |         \--- org.reactivestreams:reactive-streams:1.0.3
|    +--- com.hivemq:hivemq-mqtt-client:1.3.0
|    |    +--- io.reactivex.rxjava2:rxjava:2.2.19
|    |    |    \--- org.reactivestreams:reactive-streams:1.0.3
|    |    \--- org.reactivestreams:reactive-streams:1.0.3
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.7.21 (*)
+--- com.bosch.ourOwn.library:ourOwnLibrary:7.2.0
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.10 -> 1.7.21 (*)
+--- org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.3
|    \--- org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.3.3
|         +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.21 (*)
|         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21 -> 1.7.21
|         \--- org.jetbrains.kotlinx:kotlinx-serialization-core:1.3.3
|              \--- org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.3.3
|                   +--- org.jetbrains.kotlin:kotlin-stdlib:1.6.21 -> 1.7.21 (*)
|                   \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21 -> 1.7.21
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4
|         +--- org.jetbrains.kotlinx:kotlinx-coroutines-bom:1.6.4
|         |    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.6.4 (c)
|         |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4 (c)
|         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21 -> 1.7.21 (*)
|         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.6.21 -> 1.7.21
+--- org.springframework.statemachine:spring-statemachine-core:3.2.0 (*)
+--- org.springframework:spring-context:5.3.22
|    +--- org.springframework:spring-aop:5.3.22
|    |    +--- org.springframework:spring-beans:5.3.22 (*)
|    |    \--- org.springframework:spring-core:5.3.22 (*)
|    +--- org.springframework:spring-beans:5.3.22 (*)
|    +--- org.springframework:spring-core:5.3.22 (*)
|    \--- org.springframework:spring-expression:5.3.22
|         \--- org.springframework:spring-core:5.3.22 (*)
+--- com.hivemq:hivemq-mqtt-client:1.3.0 (*)
+--- com.hivemq:hivemq-mqtt-client-websocket:1.3.0
|    \--- com.hivemq:hivemq-mqtt-client:1.3.0 (*)
+--- com.hivemq:hivemq-mqtt-client-proxy:1.3.0
|    \--- com.hivemq:hivemq-mqtt-client:1.3.0 (*)
+--- org.slf4j:slf4j-api:1.7.36
+--- info.picocli:picocli:4.6.3
\--- ch.qos.logback:logback-classic:1.2.11
     +--- ch.qos.logback:logback-core:1.2.11
     \--- org.slf4j:slf4j-api:1.7.32 -> 1.7.36
```

...and we are integrating the plugin like this:
```
- name: Collect project dependencies
  uses: mikepenz/gradle-dependency-submission@v0.9.0
  with:
    gradle-build-module: ":"
    gradle-build-configuration: "compileClasspath"
```

**Comment by mikepenz** [comment]
Given the stacktrace the exception seems to be thrown by the underlying https://github.com/github/dependency-submission-toolkit framework. 

I don't know at this time though if it is something with the data prepared (which could be solvable from this actions perspective) or something else

**Comment by buehlerjochen** [comment]
Just discovered that it seems to be related to the branch the scan is executed on. It works on master branch (our main branch), but it fails reproducible on feature branches.
Does that make sense to you? Maybe the Dependency API only works for main branches?

**Comment by mikepenz** [comment]
I know that it only shows up on the main branch. The upload did work in the past on other branches. Possibly this was changed.
