### ISSUE TITLE
Error: Could not parse package: '+--- org.projectlombok:lombok -> 1.18.24'

### ISSUE THREAD

**Issue by neerup** [mikepenz/gradle-dependency-submission#64]
When using dependencyManagement workflow fails with

```
Error: Could not parse package: '+--- org.projectlombok:lombok -> 1.18.24'
```

example:
```
dependencies {
    implementation 'org.projectlombok:lombok'
}
dependencyManagement {
    imports {
        mavenBom "org.springframework.cloud:spring-cloud-dependencies:2021.0.3"
    }
}
```

**Comment by mikepenz** [comment]
Thank you for the report @neerup 

Will have a look into how this one differs from other scenarios.

**Comment by neerup** [comment]
Complete spring project... 
[demo.zip](https://github.com/mikepenz/gradle-dependency-submission/files/9337812/demo.zip)

**Comment by mikepenz** [comment]
@neerup thank you very much. I see now what's going on. 

Due to the usage of the bom. the dependency is not defined as:
```
+--- org.projectlombok:lombok:1.18.24
```
But instead as:
```
+--- org.projectlombok:lombok -> 1.18.24
```

Will expand the parser to handle this situations

**Comment by mikepenz** [comment]
Please try again with v0.2.0. 

Appreciate the report and the provided sample

**Comment by Srinath22N** [comment]
Currently using v0.8.0. Facing similar issue.
`Run mikepenz/gradle-dependency-submission@v0.8.0
[2](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:2)
  with:
[3](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:3)
    gradle-project-path: .
[4](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:4)
    gradle-dependency-path: build.gradle
[5](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:5)
    token: ***
[6](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:6)
    use-gradlew: true
[7](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:7)
    sub-module-mode: IGNORE
[8](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:8)
    include-build-environment: false
[9](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:10)
📘 Reading input values
[10](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:11)
  No 'gradle-build-module' passed, using ':'
[11](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:13)
🔨 Processing gradle dependencies for root module - ':'
[12](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:14)
  Completed retrieving the 'dependencies' within 37001ms
[13](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:16)
📄 Parsing gradle dependencies graph - ':'
[14](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:17)
  Dependency output of 1988 lines
[15](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:18)
  Error: Could not parse package: '\--- org.projectlombok:lombok (n)' (1)
[16](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:19)
  
[17](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:20)
  /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68
[18](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:21)
              throw Error(`The given '${pkg} can't be parsed as a gradle package.`);
[19](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:22)
  ^
[20](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:23)
  Error: The given '\--- org.projectlombok:lombok (n) can't be parsed as a gradle package.
[21](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:24)
      at parseGradlePackage (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68:1)
[22](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:25)
      at parseGradleDependency (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:166:1)
[23](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:26)
      at parseGradleGraph (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:117:1)
[24](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:27)
      at /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:195:1
[25](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:28)
      at Generator.next (<anonymous>)
[26](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:29)
      at fulfilled (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:28:1)
[27](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)`

**Comment by mikepenz** [comment]
@Srinath22N please create a new ticket for it. Also please provide the `dependency` output so we can expand the tests for this case

**Comment by Srinath22N** [comment]
Currently using v0.8.0. Facing similar issue.

```
Parsing gradle dependencies graph - ':'
[14](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:17)
  Dependency output of 1988 lines
[15](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:18)
  Error: Could not parse package: '\--- org.projectlombok:lombok (n)' (1)
[16](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:19)
  
[17](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:20)
  /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68
[18](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:21)
              throw Error(`The given '${pkg} can't be parsed as a gradle package.`);
[19](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:22)
  ^
[20](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:23)
  Error: The given '\--- org.projectlombok:lombok (n) can't be parsed as a gradle package.
[21](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:24)
      at parseGradlePackage (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:68:1)
[22](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:25)
      at parseGradleDependency (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:166:1)
[23](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:26)
      at parseGradleGraph (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/parse.js:117:1)
[24](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:27)
      at /home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:195:1
[25](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:28)
      at Generator.next (<anonymous>)
[26](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:29)
      at fulfilled (/home/runner/work/_actions/mikepenz/gradle-dependency-submission/v0.8.0/webpack:/gradle-dependency-submission/lib/process.js:28:1)
[27](https://github.com/Cowbell-Cyber/fir-account/actions/runs/3243471872/jobs/5318234548#step:3:30)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
